# Generated by Django 5.2.17 on 2026-09-23 09:00

import apps.products.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_poster_cta_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Optional hero image. The public page falls back to the poster.', null=True, upload_to='products/heroes/', validators=[apps.products.models.validate_product_poster]),
        ),
        migrations.AddField(
            model_name='product',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optional mobile screenshot shown on small screens.', null=True, upload_to='products/mobile/', validators=[apps.products.models.validate_product_poster]),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_cta_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_cta_type',
            field=models.CharField(blank=True, choices=[('contact', 'Contact form'), ('demo', 'Request demo'), ('external', 'External URL')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_cta_url',
            field=models.CharField(blank=True, help_text='Optional secondary CTA destination (external or internal path).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short line under the product name on the detail page.', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProductAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'audiences',
                'db_table': 'product_audiences',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCapabilityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_groups', to='products.product')),
            ],
            options={
                'verbose_name': 'capability group',
                'db_table': 'product_capability_groups',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('capability_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='products.productcapabilitygroup')),
            ],
            options={
                'verbose_name_plural': 'capabilities',
                'db_table': 'product_capabilities',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='products.product')),
            ],
            options={
                'verbose_name': 'control / security feature',
                'db_table': 'product_controls',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCustomSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/custom/', validators=[apps.products.models.validate_product_poster])),
                ('layout_type', models.CharField(choices=[('text', 'Text'), ('text_image', 'Text and image'), ('image_text', 'Image and text'), ('callout', 'Callout')], default='text', max_length=32)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sections', to='products.product')),
            ],
            options={
                'verbose_name': 'custom section',
                'db_table': 'product_custom_sections',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.product')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'product_faqs',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='products.product')),
            ],
            options={
                'db_table': 'product_highlights',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImplementationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementation_steps', to='products.product')),
            ],
            options={
                'verbose_name': 'implementation step',
                'db_table': 'product_implementation_steps',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='products/integrations/', validators=[apps.products.models.validate_product_poster])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='products.product')),
            ],
            options={
                'db_table': 'product_integrations',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=160, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/media/', validators=[apps.products.models.validate_product_poster])),
                ('media_type', models.CharField(choices=[('screenshot', 'Screenshot'), ('mobile', 'Mobile'), ('dashboard', 'Dashboard'), ('poster', 'Poster'), ('feature', 'Feature'), ('workflow', 'Workflow'), ('other', 'Other')], default='screenshot', max_length=32)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='products.product')),
            ],
            options={
                'verbose_name': 'product media',
                'verbose_name_plural': 'product media',
                'db_table': 'product_media',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='products.product')),
            ],
            options={
                'db_table': 'product_outcomes',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='products.product')),
            ],
            options={
                'db_table': 'product_problems',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='products.product')),
            ],
            options={
                'verbose_name': 'workflow step',
                'db_table': 'product_workflow_steps',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('highlights', 'Highlights'), ('audience', 'Audience'), ('problems', 'Problems'), ('capabilities', 'Capabilities'), ('workflow', 'Workflow'), ('media', 'Media'), ('integrations', 'Integrations'), ('controls', 'Controls'), ('outcomes', 'Outcomes'), ('implementation', 'Implementation'), ('faq', 'FAQ'), ('custom', 'Custom')], max_length=32)),
                ('title_override', models.CharField(blank=True, max_length=160, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sections', to='products.product')),
            ],
            options={
                'verbose_name': 'page section',
                'db_table': 'product_page_sections',
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'section_type'), name='uniq_product_page_section_type')],
            },
        ),
    ]
