# Generated by Django 5.2.17 on 2026-09-22 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(default='marketing_analyst', max_length=255)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('guard_name', models.CharField(default='web', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permissions',
                'unique_together': {('name', 'guard_name')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('guard_name', models.CharField(default='web', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'unique_together': {('name', 'guard_name')},
            },
        ),
        migrations.CreateModel(
            name='ModelHasPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(default='App\\Models\\User', max_length=255)),
                ('model_id', models.PositiveBigIntegerField(db_column='model_id')),
                ('permission', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.permission')),
            ],
            options={
                'db_table': 'model_has_permissions',
                'unique_together': {('permission', 'model_id', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='ModelHasRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(default='App\\Models\\User', max_length=255)),
                ('model_id', models.PositiveBigIntegerField(db_column='model_id')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
            options={
                'db_table': 'model_has_roles',
                'unique_together': {('role', 'model_id', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='RoleHasPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.permission')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
            options={
                'db_table': 'role_has_permissions',
                'unique_together': {('permission', 'role')},
            },
        ),
        migrations.CreateModel(
            name='UserAccessScope',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope_type', models.CharField(max_length=255)),
                ('scope_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_access_scopes',
                'indexes': [models.Index(fields=['user', 'scope_type'], name='user_access_user_id_c5637d_idx')],
            },
        ),
    ]
