# Generated by Django 5.2.17 on 2026-09-22 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('products', '0001_initial'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='draft', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('cta_label', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_url', models.CharField(blank=True, max_length=255, null=True)),
                ('utm', models.JSONField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('approver', models.ForeignKey(blank=True, db_column='approver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_content', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_content', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='campaigns.campaign')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='products.product')),
            ],
            options={
                'db_table': 'content_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentDestination',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('platform_override', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('external_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='social.socialaccount')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='content.contentitem')),
            ],
            options={
                'db_table': 'content_destinations',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('disk', models.CharField(default='public', max_length=255)),
                ('mime', models.CharField(blank=True, max_length=255, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_assets',
            },
        ),
        migrations.CreateModel(
            name='ContentItemMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.contentitem')),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.mediaasset')),
            ],
            options={
                'db_table': 'content_item_media',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='media',
            field=models.ManyToManyField(related_name='content_items', through='content.ContentItemMedia', to='content.mediaasset'),
        ),
    ]
