# Generated by Django 5.2.17 on 2026-09-22 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('content', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('request_type', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(default='new', max_length=255)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer', models.CharField(blank=True, max_length=255, null=True)),
                ('landing_page', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('first_responded_at', models.DateTimeField(blank=True, null=True)),
                ('lead_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='campaigns.campaign')),
                ('content_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='content.contentdestination')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='products.product')),
                ('read_by', models.ForeignKey(blank=True, db_column='read_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_leads', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, db_column='responded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(default='demo', max_length=255)),
                ('preferred_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='requested', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_demos', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demos', to='campaigns.campaign')),
                ('contact_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_requests', to='leads.contactmessage')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demos', to='products.product')),
            ],
            options={
                'db_table': 'demo_requests',
            },
        ),
        migrations.CreateModel(
            name='LeadCommunication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(default='email', max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('status', models.CharField(default='sent', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('contact_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='leads.contactmessage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_communications',
            },
        ),
    ]
