<?php

/**
 * Source of truth for Marketing Command Centre roles and permissions.
 * Seeded by PermissionSeeder. Super Admin gets every permission via Gate::before.
 */

return [
    'permissions' => [
        'dashboard.view',
        'products.view',
        'products.manage',
        'social_accounts.view',
        'social_accounts.manage',
        'content.view',
        'content.create',
        'content.edit',
        'content.delete',
        'content.approve',
        'content.publish',
        'campaigns.view',
        'campaigns.create',
        'campaigns.edit',
        'campaigns.manage',
        'analytics.view',
        'analytics.export',
        'inbox.view',
        'inbox.reply',
        'inbox.assign',
        'leads.view',
        'leads.manage',
        'leads.assign',
        'leads.export',
        'demo_requests.view',
        'demo_requests.manage',
        'users.view',
        'users.manage',
        'roles.view',
        'roles.manage',
        'integrations.view',
        'integrations.manage',
        'settings.view',
        'settings.manage',
        'audit.view',
        'careers.view',
        'careers.manage',
        'tasks.view',
        'tasks.manage',
        'blog.view',
        'blog.manage',
        'pulse.view',
        'subscribers.view',
        'subscribers.manage',
    ],

    'roles' => [
        'super_admin' => [
            'label' => 'Super Admin',
            'legacy' => 'admin',
            'permissions' => '*',
        ],
        'marketing_admin' => [
            'label' => 'Marketing Admin',
            'permissions' => [
                'dashboard.view',
                'products.view', 'products.manage',
                'social_accounts.view', 'social_accounts.manage',
                'content.view', 'content.create', 'content.edit', 'content.delete', 'content.approve', 'content.publish',
                'campaigns.view', 'campaigns.create', 'campaigns.edit', 'campaigns.manage',
                'analytics.view', 'analytics.export',
                'inbox.view', 'inbox.reply', 'inbox.assign',
                'leads.view', 'leads.manage', 'leads.assign', 'leads.export',
                'demo_requests.view', 'demo_requests.manage',
                'users.view', 'users.manage',
                'roles.view', 'roles.manage',
                'integrations.view', 'integrations.manage',
                'settings.view', 'settings.manage',
                'audit.view',
                'careers.view',
                'tasks.view', 'tasks.manage',
                'blog.view', 'blog.manage',
                'pulse.view',
                'subscribers.view', 'subscribers.manage',
            ],
        ],
        'marketing_manager' => [
            'label' => 'Marketing Manager',
            'permissions' => [
                'dashboard.view',
                'products.view', 'products.manage',
                'social_accounts.view', 'social_accounts.manage',
                'content.view', 'content.create', 'content.edit', 'content.delete', 'content.approve', 'content.publish',
                'campaigns.view', 'campaigns.create', 'campaigns.edit', 'campaigns.manage',
                'analytics.view', 'analytics.export',
                'inbox.view', 'inbox.reply', 'inbox.assign',
                'leads.view', 'leads.manage', 'leads.assign', 'leads.export',
                'demo_requests.view', 'demo_requests.manage',
                'integrations.view',
                'settings.view',
                'tasks.view', 'tasks.manage',
                'blog.view', 'blog.manage',
                'pulse.view',
                'subscribers.view',
            ],
        ],
        'social_media_manager' => [
            'label' => 'Social Media Manager',
            'permissions' => [
                'dashboard.view',
                'products.view',
                'social_accounts.view', 'social_accounts.manage',
                'content.view', 'content.create', 'content.edit', 'content.publish',
                'campaigns.view',
                'analytics.view',
                'inbox.view', 'inbox.reply', 'inbox.assign',
                'tasks.view', 'tasks.manage',
                'pulse.view',
            ],
        ],
        'content_creator' => [
            'label' => 'Content Creator',
            'permissions' => [
                'dashboard.view',
                'products.view',
                'social_accounts.view',
                'content.view', 'content.create', 'content.edit',
                'campaigns.view',
                'analytics.view',
                'tasks.view',
                'blog.view', 'blog.manage',
            ],
        ],
        'community_manager' => [
            'label' => 'Community Manager',
            'permissions' => [
                'dashboard.view',
                'products.view',
                'social_accounts.view',
                'content.view',
                'analytics.view',
                'inbox.view', 'inbox.reply', 'inbox.assign',
                'leads.view',
                'tasks.view',
                'pulse.view',
            ],
        ],
        'growth_marketer' => [
            'label' => 'Growth / Performance Marketer',
            'permissions' => [
                'dashboard.view',
                'products.view',
                'social_accounts.view',
                'content.view',
                'campaigns.view', 'campaigns.create', 'campaigns.edit',
                'analytics.view', 'analytics.export',
                'leads.view',
                'demo_requests.view',
                'tasks.view',
                'pulse.view',
                'subscribers.view',
            ],
        ],
        'sales_lead_manager' => [
            'label' => 'Sales / Lead Manager',
            'permissions' => [
                'dashboard.view',
                'products.view',
                'leads.view', 'leads.manage', 'leads.assign', 'leads.export',
                'demo_requests.view', 'demo_requests.manage',
                'campaigns.view',
                'analytics.view',
                'tasks.view', 'tasks.manage',
            ],
        ],
        'marketing_analyst' => [
            'label' => 'Marketing Analyst / Viewer',
            'permissions' => [
                'dashboard.view',
                'products.view',
                'social_accounts.view',
                'content.view',
                'campaigns.view',
                'analytics.view', 'analytics.export',
                'leads.view',
                'demo_requests.view',
                'pulse.view',
                'subscribers.view',
                'blog.view',
            ],
        ],
        'hr_manager' => [
            'label' => 'HR Manager',
            'legacy' => 'hr_manager',
            'permissions' => [
                'careers.view',
                'careers.manage',
            ],
        ],
    ],
];
