<?php

return [
    'company' => 'Prady Technologies Ltd',
    'tagline' => 'Doing It Differently',
    'products' => [
        [
            'slug' => 'prady-microfinance',
            'name' => 'Prady Microfinance',
            'short' => 'Complete operating platform for MFIs and lenders.',
            'description' => 'A complete operating platform for microfinance institutions and lenders: customers, loans, collections, payments, M-Pesa, accounting, reporting, HR, controls, and institutional operations.',
            'market' => 'MFIs, credit companies, lenders',
            'icon' => 'finance',
            'featured' => true,
        ],
        [
            'slug' => 'rafiki-loan',
            'name' => 'Rafiki Loan',
            'short' => 'Digital lending marketplace connecting borrowers and capital.',
            'description' => 'A digital lending marketplace where people seeking financing can connect with people and institutions offering financing. The platform manages discovery, matching, and the journey between borrower and finance provider.',
            'market' => 'Borrowers + lenders / capital providers',
            'icon' => 'handshake',
            'featured' => true,
        ],
        [
            'slug' => 'gps-hosting',
            'name' => 'GPS Hosting & Tracking',
            'short' => 'Affordable GPS hosting and Prady-branded trackers.',
            'description' => 'A platform capable of hosting compatible GPS trackers for customers seeking an affordable, reliable alternative. Target offer: KES 700 per tracker per year. Also supports Prady-branded GPS devices sourced and configured under our own offering.',
            'market' => 'Vehicle owners, fleets, logistics, GPS resellers',
            'icon' => 'location',
            'featured' => true,
        ],
        [
            'slug' => 'property-management',
            'name' => 'Property Management System',
            'short' => 'Manage properties, tenants, leases, rent and maintenance.',
            'description' => 'A platform for managing properties, units, tenants, leases, rent, payments, arrears, maintenance, and property performance.',
            'market' => 'Landlords, property managers, real-estate businesses',
            'icon' => 'building',
            'featured' => true,
        ],
        [
            'slug' => 'spareme',
            'name' => 'SpareMe',
            'short' => 'Vehicle-first automotive commerce and intelligence.',
            'description' => 'A vehicle-first automotive commerce and intelligence ecosystem. Vehicle owners identify exact vehicles; dealers manage POS and inventory; compatible spare parts are matched to vehicles; mechanics, suppliers, and logistics participate in the ecosystem.',
            'market' => 'Vehicle owners, parts dealers, mechanics, suppliers, garages',
            'icon' => 'car',
            'featured' => false,
        ],
        [
            'slug' => 'live-commerce',
            'name' => 'Live Commerce Platform',
            'short' => 'Social selling with live shows and lasting product shelves.',
            'description' => 'A social-commerce intelligence platform where sellers and creators announce upcoming live shows, attract audiences to those live sessions, and continue showcasing the products discussed after the broadcast has ended.',
            'market' => 'Social sellers, creators, SMEs, online merchants',
            'icon' => 'live',
            'featured' => false,
        ],
        [
            'slug' => 'sacco-system',
            'name' => 'SACCO System',
            'short' => 'Digital operating system for SACCOs and member institutions.',
            'description' => 'A digital operating system for SACCO and member institutions covering membership, savings/contributions, loans, accounts, governance, and institutional administration.',
            'market' => 'SACCOs and member-based financial institutions',
            'icon' => 'users',
            'featured' => false,
        ],
        [
            'slug' => 'chama-system',
            'name' => 'Chama System',
            'short' => 'Simple platform for investment groups and welfare chamas.',
            'description' => 'A simpler platform specifically for investment groups and chamas: members, contributions, welfare, loans, projects/investments, commitments, documents, and transparent group accounts.',
            'market' => 'Chamas, investment clubs, welfare groups',
            'icon' => 'group',
            'featured' => false,
        ],
        [
            'slug' => 'mtalii-travel-wallet',
            'name' => 'Mtalii Travel Wallet',
            'short' => 'Tourism-focused wallet for payments, FX and merchants.',
            'description' => 'A tourism-focused wallet and travel application designed around tourists and local merchants: payments, FX, merchant acceptance, and tourism-oriented financial services.',
            'market' => 'Tourists, tour operators, guides, local merchants',
            'icon' => 'wallet',
            'featured' => false,
        ],
    ],
];
