# Generated by Django 5.2.17 on 2026-09-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_contactchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactchannel',
            name='channel_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'X / Twitter'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('github', 'GitHub'), ('website', 'Website / Link'), ('location', 'Location'), ('hours', 'Business hours'), ('other', 'Other / custom link')], max_length=32),
        ),
    ]
