# Generated by Django 5.2.17 on 2026-09-22 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('content', '0001_initial'),
        ('products', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAlert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule_key', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=255)),
                ('status', models.CharField(default='open', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='campaigns.campaign')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='products.product')),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='social.socialaccount')),
            ],
            options={
                'db_table': 'marketing_alerts',
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('measurable_type', models.CharField(max_length=255)),
                ('measurable_id', models.PositiveBigIntegerField()),
                ('source', models.CharField(max_length=255)),
                ('metric_key', models.CharField(max_length=255)),
                ('raw_key', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'metric_snapshots',
                'unique_together': {('measurable_type', 'measurable_id', 'source', 'metric_key', 'captured_at')},
            },
        ),
        migrations.CreateModel(
            name='TrackedLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('destination_url', models.CharField(max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
                ('click_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_links', to='campaigns.campaign')),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_links', to='content.contentitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_links', to='products.product')),
            ],
            options={
                'db_table': 'tracked_links',
            },
        ),
        migrations.CreateModel(
            name='WebsiteEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_events', to='campaigns.campaign')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_events', to='products.product')),
                ('tracked_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_events', to='analytics.trackedlink')),
            ],
            options={
                'db_table': 'website_events',
            },
        ),
    ]
