MARKETING_PERMISSIONS = [
    "dashboard.view",
    "products.view",
    "products.manage",
    "social_accounts.view",
    "social_accounts.manage",
    "content.view",
    "content.create",
    "content.edit",
    "content.delete",
    "content.approve",
    "content.publish",
    "campaigns.view",
    "campaigns.create",
    "campaigns.edit",
    "campaigns.manage",
    "analytics.view",
    "analytics.export",
    "inbox.view",
    "inbox.reply",
    "inbox.assign",
    "leads.view",
    "leads.manage",
    "leads.assign",
    "leads.export",
    "demo_requests.view",
    "demo_requests.manage",
    "users.view",
    "users.manage",
    "roles.view",
    "roles.manage",
    "integrations.view",
    "integrations.manage",
    "settings.view",
    "settings.manage",
    "audit.view",
    "careers.view",
    "careers.manage",
    "tasks.view",
    "tasks.manage",
    "blog.view",
    "blog.manage",
    "pulse.view",
    "subscribers.view",
    "subscribers.manage",
]

ROLE_PERMISSIONS = {
    "super_admin": "*",
    "marketing_admin": [p for p in MARKETING_PERMISSIONS if p != "careers.manage"],
    "hr_manager": ["careers.view", "careers.manage"],
}
