# Generated by Django 5.2.17 on 2026-09-22 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=255)),
                ('status', models.CharField(default='disconnected', max_length=255)),
                ('external_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scopes', models.JSONField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'integrations',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='active', max_length=255)),
                ('token_status', models.CharField(default='unknown', max_length=255)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_posted_at', models.DateTimeField(blank=True, null=True)),
                ('follower_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('can_publish', models.BooleanField(default=True)),
                ('can_analytics', models.BooleanField(default=True)),
                ('can_inbox', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to='social.integration')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to='products.product')),
            ],
            options={
                'db_table': 'social_accounts',
            },
        ),
    ]
